### ISSUE TITLE
In section 2, "and now what?"

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/databases#1]
Looks like you left a note to yourself here. Given the context, you should probably:

- Explain more explicitly what's happening...that we're running SQL statements from inside Python. That's going to be confusing, at least a little bit.
- Explain more about what tables, records, and fields represent, in abstract terms. (A record in a table is one istance of a category, i.e. a book or a person, and the field is an aspect of that record.

**Comment by szweibel** [comment]
Done
