### ISSUE TITLE
Back link returning 404

### ISSUE THREAD

**Issue by peakera** [DHRI-Curriculum/databases#15]
The back links at top and bottom of page on https://github.com/DHRI-Curriculum/databases/blob/master/sections/9b-datasets.md return 404 errors.

**Comment by kallewesterling** [comment]
@szweibel I have addressed this issue - see above. Do you think you'll have a moment to resolve it?

**Comment by szweibel** [comment]
Taken care of just now.

**Comment by kallewesterling** [comment]
Thank you!
