### ISSUE TITLE
sql cheatsheet link

### ISSUE THREAD

**Issue by kchatlosh** [DHRI-Curriculum/databases#16]
I tried to open the sql cheatsheet link from resources.md (https://github.com/DHRI-Curriculum/databases/blob/master/resources.md) and I got an error message -- it looks like the link isn't working

**Comment by kallewesterling** [comment]
Not sure where the file has gone but it was around a year from today:
https://github.com/DHRI-Curriculum/databases/commit/e30914466a5f7ca3094cadfeedb1f61b88e069ad

What do you think? Should I just revive this file?

**Comment by kallewesterling** [comment]
Not sure where the file has gone but it was around a year from today:
https://github.com/DHRI-Curriculum/databases/commit/e30914466a5f7ca3094cadfeedb1f61b88e069ad

What do you think? Should I just revive this file?

**Comment by szweibel** [comment]
Yes, please revive!

**Comment by kallewesterling** [comment]
Fixed! See https://github.com/DHRI-Curriculum/databases/commit/4965ad5414782699f51e8d3718d67735885440a7!
