### ISSUE TITLE
Section 3, add longer explaantion

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/databases#4]
You added a placeholder here for a longer explanation, agree that there should be one.

**Comment by szweibel** [comment]
Hm, what about?

**Comment by smythp** [comment]
I'm referring to the "be pythonic" section.

https://github.com/DHRI-Curriculum/databases/blob/master/sections/3b-pythonic.md

Remember that other people will be teaching from this, so we can't rely on being in the room and giving the correct answer. I wouldn't leave questions hanging. If you ask rhetorically what the purpose of it is, you should say the answer explicitly.

PS When you give that page a title, don't forgot to make sure it's in the table of contents.

**Comment by szweibel** [comment]
Ok, done

**Comment by smythp** [comment]
I know you probably haven't pushed this yet but you're killing me when I still see the placeholder :(

**Comment by smythp** [comment]
You can close out the issue in the commit message, which is nice because then you can see the commit that resolved it. "Fixes #4"
