### ISSUE TITLE
Example in 7 won't work

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/databases#7]
First, there is no cursor object in createdb. There is only the conn or database connection object.

Second, even if there was a cursor object, you would need to use createdb.cursor or import the cursor object directly with from createdb import cursor.

**Comment by szweibel** [comment]
Did you change this or did I? Because it looks fine now.

**Comment by smythp** [comment]
I think you did. I made these issues before I thought to pull in your changes, sorry.
