### ISSUE TITLE
Put python scripts in root directory into a folder

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/databases#9]

**Comment by szweibel** [comment]
done

**Comment by smythp** [comment]
Is this done? I'm seeing all the .py files in the root directory still.

**Comment by szweibel** [comment]
Yes, just hadn't pushed it yet.

**Comment by smythp** [comment]
Figured that was the issue, thanks. Do you want to do the same with the database files (put them in a folder) or remove them? I've found that if there are too many files and people can't see the readme right away, they get confused.
